export const IMG_CDN_URL =
  'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

export const RestaurantList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '503961',
      name: 'Istah - The Mediterranean Way',
      uuid: '8d627ab5-8cd7-4195-a37e-aeb89416ceef',
      city: '1',
      area: 'Santhi Nagar',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: '9a01f2935fcb5ae05426db8264062102',
      cuisines: [
        'Arabian',
        'Biryani',
        'Mediterranean',
        'Lebanese',
        'Snacks',
        'Beverages',
      ],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 32,
      minDeliveryTime: 30,
      maxDeliveryTime: 40,
      slaString: '30-40 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant:
          'istah---shawarma-and-biryani-central-bangalore-central-bangalore',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        '# 299,1st Floor, BBMP ward no 117, Akkithimanahalli , Shanthinagar, Bangalore 560025.',
      locality: 'Akkithimanahalli',
      parentId: 3518,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: '50% off',
        shortDescriptionList: [
          {
            meta: '50% off | Use TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '50% off up to ₹85 | Use code TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '50% OFF',
        shortDescriptionList: [
          {
            meta: 'Use TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '50% off up to ₹85 | Use code TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      ribbon: [{ type: 'PROMOTED' }],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=5992034~p=1~eid=00000186-7efa-f701-2a2b-63820086011a',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '503961',
        deliveryTime: 32,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.3',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '3241',
      name: 'Meghana Foods',
      uuid: '93695df0-56e1-417e-b9a8-32084ebaadaf',
      city: '1',
      area: 'Ashok Nagar',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'e0vvulfbahjxjz6k4uwi',
      cuisines: [
        'Biryani',
        'Andhra',
        'South Indian',
        'North Indian',
        'Chinese',
        'Seafood',
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 24,
      minDeliveryTime: 20,
      maxDeliveryTime: 30,
      slaString: '20-30 MINS',
      lastMileTravel: 2.4000000953674316,
      slugs: {
        restaurant: 'meghana-foods-central-bangalore',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        '57/1, 1st Floor, Jayalaxmi Chambers, Next to Old Galaxy Theatre,Residency Road, Bangalore',
      locality: 'Residency Road',
      parentId: 635,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: 'FREE DELIVERY',
        shortDescriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [
          {
            meta: 'Free Delivery',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.4 kms',
      hasSurge: false,
      sla: {
        restaurantId: '3241',
        deliveryTime: 24,
        minDeliveryTime: 20,
        maxDeliveryTime: 30,
        lastMileTravel: 2.4000000953674316,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.5',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '121603',
      name: 'Kannur Food Point',
      uuid: '51983905-e698-4e31-b0d7-e376eca56320',
      city: '1',
      area: 'Tavarekere',
      totalRatingsString: '5000+ ratings',
      cloudinaryImageId: 'bmwn4n4bn6n1tcpc8x2h',
      cuisines: ['Kerala', 'Chinese'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 34,
      minDeliveryTime: 30,
      maxDeliveryTime: 40,
      slaString: '30-40 MINS',
      lastMileTravel: 6.5,
      slugs: {
        restaurant: 'kannur-food-point-btm',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        '6/21,9TH CROSS ,1ST MAIN, VENKATESHWARA LAYOUT,SG PALYA, BENGALURU, - 560093',
      locality: 'SG Palya',
      parentId: 20974,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: '50% off',
        shortDescriptionList: [
          {
            meta: '50% off on all orders',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '50% off on all orders',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '50% OFF',
        shortDescriptionList: [
          {
            meta: 'Free Delivery',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '50% off on all orders',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '6.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '121603',
        deliveryTime: 34,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        lastMileTravel: 6.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.8',
      totalRatings: 5000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '430368',
      name: 'Kebapci',
      uuid: '3a4d0b1f-6de7-4b09-b755-5220872d0c75',
      city: '1',
      area: 'Koramangala',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'exqdoyydk9zuqr7jfphr',
      cuisines: ['Turkish', 'Middle Eastern', 'Lebanese'],
      tags: [],
      costForTwo: 60000,
      costForTwoString: '₹600 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 40,
      maxDeliveryTime: 50,
      slaString: '40-50 MINS',
      lastMileTravel: 6.699999809265137,
      slugs: {
        restaurant: 'kebapci-koramangala-koramangala',
        city: 'bangalore',
      },
      cityState: '1',
      address: '"No. 74, 17E Main Road, 6th Block, Koramangala , Bangalore\t"',
      locality: '6th Block',
      parentId: 17445,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: 'FREE DELIVERY',
        shortDescriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [
          {
            meta: 'Free Delivery',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      ribbon: [{ type: 'PROMOTED' }],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=5991252~p=4~eid=00000186-7efa-f701-2a2b-638300860435',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '6.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '430368',
        deliveryTime: 42,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        lastMileTravel: 6.699999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.3',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '30531',
      name: 'Hotel Empire',
      uuid: 'b6535450-6f4c-434f-8cae-425317928346',
      city: '1',
      area: 'Brigade Road',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'qltgnkyywuo5gmnpqzbm',
      cuisines: ['North Indian', 'Kebabs', 'Biryani'],
      tags: [],
      costForTwo: 45000,
      costForTwoString: '₹450 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 25,
      maxDeliveryTime: 35,
      slaString: '25-35 MINS',
      lastMileTravel: 2.200000047683716,
      slugs: {
        restaurant: 'empire-restaurant-central-bangalore-central-bangalore',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        'Empire SuitesNo.35, Castle Street, Off Brigade Road,Bengaluru, Karnataka 560025',
      locality: '',
      parentId: 475,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: '10% off',
        shortDescriptionList: [
          {
            meta: '10% off | Use TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '10% off up to ₹40 | Use code TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '10% OFF',
        shortDescriptionList: [
          {
            meta: 'Use TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: '10% off up to ₹40 | Use code TRYNEW',
            discountType: 'Percentage',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.2 kms',
      hasSurge: false,
      sla: {
        restaurantId: '30531',
        deliveryTime: 26,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        lastMileTravel: 2.200000047683716,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.3',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '306639',
      name: 'The Coorg Food Co.',
      uuid: '318c2c99-1173-42a8-b56c-f655e3cc5ffd',
      city: '1',
      area: 'Koramangala',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'ej90ytd5x7ffyl6ii7cn',
      cuisines: ['South Indian'],
      tags: [],
      costForTwo: 75000,
      costForTwoString: '₹750 FOR TWO',
      deliveryTime: 41,
      minDeliveryTime: 40,
      maxDeliveryTime: 50,
      slaString: '40-50 MINS',
      lastMileTravel: 6.5,
      slugs: {
        restaurant: 'the-coorg-food-co.-koramangala-koramangala',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        'No 466, Ground floor shop, 17th G main, 6th block, 80 feet road, opp BMTC Bus Depot, Koramangala, Bangalore',
      locality: '6th Block',
      parentId: 207214,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: 'FREE DELIVERY',
        shortDescriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'Free Pudding on orders above ₹717',
            discountType: 'Freebie',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'Free Pudding on orders above ₹717',
            discountType: 'Freebie',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [
          {
            meta: 'Free Delivery',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
          {
            meta: 'Free Pudding on orders above ₹717',
            discountType: 'Freebie',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      ribbon: [{ type: 'PROMOTED' }],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=5937048~p=7~eid=00000186-7efa-f701-2a2b-63840086076a',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '6.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '306639',
        deliveryTime: 41,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        lastMileTravel: 6.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.3',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '447965',
      name: 'ZAMA',
      uuid: '289647f9-a72f-4316-85a3-9a9e2e4d6338',
      city: '1',
      area: 'Indiranagar',
      totalRatingsString: '50+ ratings',
      cloudinaryImageId: 'kkzqxnjaicpsemmxk5td',
      cuisines: ['Turkish'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 38,
      minDeliveryTime: 35,
      maxDeliveryTime: 45,
      slaString: '35-45 MINS',
      lastMileTravel: 5.699999809265137,
      slugs: {
        restaurant: 'zama-indiranagar-indiranagar',
        city: 'bangalore',
      },
      cityState: '1',
      address:
        '303, Ground Floor, Ashok Terrace, 100 Feet Road, Indiranagar, Bangalore',
      locality: '100 Feet Road',
      parentId: 269737,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: 'Flat ₹150 off',
        shortDescriptionList: [
          {
            meta: 'Flat ₹150 off on orders above ₹799',
            discountType: 'Flat',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'Flat ₹150 off on orders above ₹799 | Use code FLAT150',
            discountType: 'Flat',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '₹150 OFF',
        shortDescriptionList: [
          {
            meta: 'Use FLAT150',
            discountType: 'Flat',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'Flat ₹150 off on orders above ₹799 | Use code FLAT150',
            discountType: 'Flat',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      ribbon: [{ type: 'PROMOTED' }],
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=5804183~p=10~eid=00000186-7efa-f701-2a2b-638500860a47',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '5.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '447965',
        deliveryTime: 38,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        lastMileTravel: 5.699999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 50,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '424558',
      name: "La Pino'z Pizza",
      uuid: '8148a6cf-ec13-4800-a649-285af0ac2364',
      city: '1',
      area: 'Basavanagudi',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: 'mocil3npmwpcdcfaxql1',
      cuisines: ['Pizzas'],
      tags: [],
      costForTwo: 22000,
      costForTwoString: '₹220 FOR TWO',
      deliveryTime: 33,
      minDeliveryTime: 30,
      maxDeliveryTime: 40,
      slaString: '30-40 MINS',
      lastMileTravel: 4.400000095367432,
      slugs: {
        restaurant: "la-pino'z-pizza-basavanagudi-basavanagudi",
        city: 'bangalore',
      },
      cityState: '1',
      address: 'No.99, Gandhi Bazaar Main road, Basavanagudi, Bengaluru',
      locality: 'Gandhi Bazaar Main Road',
      parentId: 4961,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: 'FREE DELIVERY',
        shortDescriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [
          {
            meta: 'Free Delivery',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        descriptionList: [
          {
            meta: 'FREE DELIVERY',
            discountType: 'FREE_DELIVERY',
            operationType: 'RESTAURANT',
          },
        ],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [],
        totalFees: 0,
        message: '',
        title: '',
        amount: '',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.4 kms',
      hasSurge: false,
      sla: {
        restaurantId: '424558',
        deliveryTime: 33,
        minDeliveryTime: 30,
        maxDeliveryTime: 40,
        lastMileTravel: 4.400000095367432,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.9',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
];
